### ISSUE TITLE
Run commands in a shell

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/overmind-agent#18]
The `command` source currently runs commands without any shell, this means that things like shell builtins won't work (e.g. `echo`). It also means that the environment won't be loaded in the way that users expect and things like additions to the $PATH might be missing.

Commands should be run within a shell by default (bash on Linux and powershell on windows).

## Questions

**Should users be able to specify the shell?**

Maybe, since each shell will need its own arguments though (especially on windows) this won't be able to be completely dynamic, probably more like an approved list

**What options should be exposed around shell customisations?**

* [x] Working directory
* [x] STDIN
* [x] Environment variables (Make sure these are appended and that we don't remove any environment variables we might otherwise need)
* [x] Timeout
* [x] User to run as

## Tasks

* [x] Work out how Golang is going to deal with the encoding of the text that we return. Is this going to be a problem?
* [x] #19
